local builtin = require('telescope.builtin')
vim.keymap.set('n', '<leader>pf', builtin.find_files, { desc = "Project find files" })
vim.keymap.set('n', '<C-p>', builtin.git_files, { desc = "Show git files" })
vim.keymap.set('n', '<leader>ps', function()
    builtin.grep_string({ search = vim.fn.input("Grep > ") })
end, { desc = "Project search string" })

vim.keymap.set('n', '<leader>bf', "<cmd>Telescope buffers<CR>", { desc = "Buffer select" })
vim.keymap.set("n", "H", "<cmd>bprev<CR>", { desc = "Prev buffer" })
vim.keymap.set("n", "L", "<cmd>bnext<CR>", { desc = "Next buffer" })
